# Generated by Django 5.0.6 on 2026-05-22 06:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PitchCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('amount_needed', models.DecimalField(decimal_places=2, max_digits=15)),
                ('funding_status', models.CharField(choices=[('open', 'Open'), ('funded', 'Funded'), ('in_review', 'In Review'), ('closed', 'Closed')], default='open', max_length=20)),
                ('stage', models.CharField(choices=[('idea', 'Idea'), ('mvp', 'MVP'), ('growth', 'Growth'), ('scale', 'Scale')], default='idea', max_length=20)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pitches/images/')),
                ('media', models.JSONField(blank=True, default=list)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entrepreneur', models.ForeignKey(limit_choices_to={'role': 'entrepreneur'}, on_delete=django.db.models.deletion.CASCADE, related_name='pitches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pitches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PitchBookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_pitches', to=settings.AUTH_USER_MODEL)),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitch_bookmarks', to='pitches.pitchcard')),
            ],
            options={
                'db_table': 'pitch_bookmarks',
                'unique_together': {('user', 'pitch')},
            },
        ),
        migrations.CreateModel(
            name='PitchLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitch_likes', to='pitches.pitchcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_pitches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pitch_likes',
                'unique_together': {('user', 'pitch')},
            },
        ),
    ]
