# Generated by Django 5.0.6 on 2026-05-22 06:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pitches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_ending', models.DateField()),
                ('summary', models.TextField()),
                ('wins', models.TextField()),
                ('blockers', models.TextField(blank=True, default='')),
                ('next_steps', models.TextField()),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entrepreneur', models.ForeignKey(limit_choices_to={'role': 'entrepreneur'}, on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to=settings.AUTH_USER_MODEL)),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='pitches.pitchcard')),
            ],
            options={
                'db_table': 'weekly_progress',
                'ordering': ['-week_ending'],
                'unique_together': {('pitch', 'week_ending')},
            },
        ),
    ]
