services:
  - type: web
    name: grantbridge-backend
    runtime: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --log-level info --preload
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: grantbridge-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: ".onrender.com,grantbridge-backend-2.onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://grantbridge-frontend.vercel.app"
      - key: FRONTEND_URL
        value: "https://grantbridge-frontend.vercel.app"
      - key: PAYSTACK_SECRET_KEY
        value: "sk_test_d6952f8816fc458dc306386319da82bca4e20f6a"
      - key: PAYSTACK_PUBLIC_KEY
        value: "pk_test_36637e4b0b7603e563d59c3f4cbd436e9a092079"
      - key: CLOUDINARY_URL
        value: "cloudinary://959944263569935:-MlNvh0O_u3m2PwrpZD3AJ_tYEs@dfdswk0l7"
      - key: EMAIL_HOST_USER
        value: "suzywizzy6@gmail.com"
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        value: "GrantBridge <suzywizzy6@gmail.com>"
      - key: ADMIN_EMAIL
        value: "suzywizzy6@gmail.com"
      - key: ADMIN_PASSWORD
        value: "GrantBridge@Admin2026"

databases:
  - name: grantbridge-db
    databaseName: grantbridge
    user: grantbridge
    plan: free
