# Generated by Django 5.0.6 on 2026-05-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_bio_user_location_user_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
