# Generated by Django 5.0.6 on 2026-05-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationdocument',
            name='id_type',
            field=models.CharField(max_length=30),
        ),
    ]
